/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TimeSlotNew;

import java.awt.List;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import timetablemanagement.DbConn;

/**
 *
 * @author asvin
 */
public class AddTimeSlot extends javax.swing.JFrame {

     Connection conn = null;
     PreparedStatement pst = null;
    ResultSet result = null;
     
     
    /**
     * Creates new form AddTimeSlot
     */
    public AddTimeSlot() {
        initComponents();
        conn = DbConn.ConnecrDb ();
        setStudentGroup();
        UpDateComboBatch();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    private void setStudentGroup(){
        
        try{
            String query="select DISTINCT student_group from session1";
            
            pst = conn.prepareStatement(query);
            result = pst.executeQuery();
            
            while(result.next()){
               
                System.out.println(result.getString("student_group"));
                StudentGroup.addItem(result.getString("student_group"));
            }
            
             
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
    //******************************************************
    
    private void setSessionDetails(String sid){
        try{
            String sql ="select * from session1 where session_id ='"+sid+"'";
            
            pst = conn.prepareStatement(sql);
            result = pst.executeQuery();
            
            
                String subject_nameData = result.getString("subject");
                String subjectIDData = result.getString("subject_code");
                String sessionIDData = result.getString("session_id");
                String tagData = result.getString("tag");
                String groupData = result.getString("student_group");
//               String noOfStudentData = result.getString("number_of_student");
                String durationData = result.getString("duration");
                tag.setText(tagData);
                group.setText(groupData);
                subject.setText(subject_nameData);
                subject_code.setText("("+subjectIDData+")");
//                noOfStudent.setText(noOfStudentData);
                duration.setText("("+durationData+")");
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void setSessionLectureDetails(String sid){
        try{
            String sql ="select * from sessionLectures where sessionID ='"+sid+"'";
            
            pst = conn.prepareStatement(sql);
            result = pst.executeQuery();
            String name="";
            while(result.next()){
                name =name+""+ result.getString("lectureName")+", ";
                System.out.println(name);
            }
            
              System.out.println(name);
                lectureName.setText(name);
                 
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
         
    
   private void setSeissionCombo(String groupSearch){
     
     int itemCount = setSession.getItemCount();
     
        try{
            String sql ="select * from session1 where student_group='"+groupSearch+"'";
            
            pst = conn.prepareStatement(sql);
            result = pst.executeQuery();

           
           while(result.next()){
              
               
                    setSession.addItem(result.getString("session_id"));
                  
            }
           for(int i=0;i<itemCount;i++){
                            setSession.removeItemAt(0);
                         }
  

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
   
    private void UpDateComboRoom(String sid ){
               
        String sql = "select room from sessionRoom where sessionId='"+sid+"'";
        
        try{
            pst = conn.prepareStatement(sql);
            result = pst.executeQuery();
            
            String out = result.getString("room");
            
            if(result.next()){
                roomText.setText(out);
            }else if(result.wasNull()){
                //not in use
                roomText.removeAll();
            }           
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
   
    private void UpDateComboBatch(){
        String sql = "SELECT * FROM workingdays";
        try{
            pst = conn.prepareStatement(sql);
            result = pst.executeQuery();
            while(result.next()){
                batchComboBox.addItem(result.getString("batch"));
            }
        }        
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
     private void UpDateComboDays(String setBatch ){
         int itemCount = DayComboBox.getItemCount();
         for(int i=0;i<itemCount;i++){
             DayComboBox.removeItemAt(0);                         
         }
        String sql = "SELECT * FROM day where batch='"+setBatch+"'";
        try{
            pst = conn.prepareStatement(sql);
            result = pst.executeQuery();            
            while(result.next()){
                DayComboBox.addItem(result.getString("days"));
            }

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
     
     private void UpDateComboTimeslot(String setBatch){
         int itemCount = timeComboBox.getItemCount();
         for(int i=0;i<itemCount;i++){
             timeComboBox.removeItemAt(0);                         
         }
        String sql = "SELECT * FROM timeSlot where batch='"+setBatch+"'";
        try{
            pst = conn.prepareStatement(sql);
            result = pst.executeQuery();
            while(result.next()){
                timeComboBox.addItem(result.getString("time_slot"));
            }
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
   
        
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mainpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        StudentGroup = new javax.swing.JComboBox<>();
        addBut = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        roomText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        setSession = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        tag = new javax.swing.JLabel();
        group = new javax.swing.JLabel();
        subject = new javax.swing.JLabel();
        subject_code = new javax.swing.JLabel();
        duration = new javax.swing.JLabel();
        lectureName = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        batchComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        DayComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        timeComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tag1 = new javax.swing.JLabel();
        group1 = new javax.swing.JLabel();
        subject1 = new javax.swing.JLabel();
        subject_code1 = new javax.swing.JLabel();
        duration1 = new javax.swing.JLabel();
        lectureName1 = new javax.swing.JLabel();
        addTime = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Add TimeSlots");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Student Group:");

        StudentGroup.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        StudentGroup.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                StudentGroupItemStateChanged(evt);
            }
        });
        StudentGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentGroupActionPerformed(evt);
            }
        });

        addBut.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addBut.setText("ADD");
        addBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Room:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Session:");

        setSession.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        setSession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        setSession.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                setSessionItemStateChanged(evt);
            }
        });
        setSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setSessionActionPerformed(evt);
            }
        });

        tag.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tag.setText("Tag");

        group.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        group.setText("Group");

        subject.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        subject.setText("Subject");

        subject_code.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        subject_code.setText("Subject Code");

        duration.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        duration.setText("Duration");

        lectureName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lectureName.setText("Lecturer");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tag)
                    .addComponent(group)
                    .addComponent(subject)
                    .addComponent(subject_code)
                    .addComponent(duration)
                    .addComponent(lectureName))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(tag)
                .addGap(2, 2, 2)
                .addComponent(group)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subject_code)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(duration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lectureName)
                .addContainerGap())
        );

        batchComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        batchComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                batchComboBoxItemStateChanged(evt);
            }
        });
        batchComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                batchComboBoxMouseClicked(evt);
            }
        });
        batchComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchComboBoxActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Days:");

        DayComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("TimeSlot:");

        timeComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Batch:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Select Details");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(204, 204, 204))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel4))
                            .addGap(70, 70, 70)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(batchComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DayComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(timeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(batchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(DayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(timeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        tag1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tag1.setText("Tag");

        group1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        group1.setText("Group");

        subject1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        subject1.setText("Subject");

        subject_code1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        subject_code1.setText("Subject Code");

        duration1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        duration1.setText("Duration");

        lectureName1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lectureName1.setText("Lecturer");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel3)))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roomText, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(setSession, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tag1)
                    .addComponent(group1)
                    .addComponent(subject1)
                    .addComponent(subject_code1)
                    .addComponent(duration1)
                    .addComponent(lectureName1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tag1)
                        .addGap(2, 2, 2)
                        .addComponent(group1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subject1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subject_code1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(duration1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lectureName1)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        addTime.setText("Add");
        addTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainpanelLayout = new javax.swing.GroupLayout(mainpanel);
        mainpanel.setLayout(mainpanelLayout);
        mainpanelLayout.setHorizontalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanelLayout.createSequentialGroup()
                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(StudentGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addBut))
                    .addGroup(mainpanelLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(addTime)))
                .addContainerGap(419, Short.MAX_VALUE))
        );
        mainpanelLayout.setVerticalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(StudentGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBut))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addTime)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(476, 476, 476)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 149, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StudentGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentGroupActionPerformed

    private void setSessionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_setSessionItemStateChanged
        // TODO add your handling code here:
           setSessionDetails(setSession.getSelectedItem().toString()) ;
           setSessionLectureDetails(setSession.getSelectedItem().toString());
           UpDateComboRoom(setSession.getSelectedItem().toString());
           UpDateComboDays(batchComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_setSessionItemStateChanged

    private void StudentGroupItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_StudentGroupItemStateChanged
        // TODO add your handling code here:      
        
    }//GEN-LAST:event_StudentGroupItemStateChanged

    private void addButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButActionPerformed
        // TODO add your handling code here:      
        setSeissionCombo(StudentGroup.getSelectedItem().toString());               
    }//GEN-LAST:event_addButActionPerformed

    private void setSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setSessionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setSessionActionPerformed

    private void batchComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchComboBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_batchComboBoxActionPerformed

    private void batchComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_batchComboBoxItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_batchComboBoxItemStateChanged

    private void batchComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batchComboBoxMouseClicked
        // TODO add your handling code here:
        UpDateComboTimeslot(batchComboBox.getSelectedItem().toString());
        UpDateComboDays(batchComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_batchComboBoxMouseClicked

    private void addTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTimeActionPerformed
        // TODO add your handling code here:
             // TODO add your handling code here:
        //add timeSlots---db timetable
        
        String sql = "INSERT into timetable(session,room,studentGroup,batch,day,timeSlot) VALUES(?,?,?,?,?,?)";
        
        //String column_X = date;
        //String timeslot_y = timeslot;
        //String session_z = session;
        
        // String sql = "insert into dashtable(column_X) values(session_z) where timeslot=timeslot_y";
        try{
            pst = conn.prepareStatement(sql);
            String t_tag = tag.getText().toString();
            String t_group = group.getText().toString();
            String t_subject = subject.getText().toString();
            String t_subject_code = subject_code.getText().toString();
            String t_duration = duration.getText().toString();
            String t_lectureName = lectureName.getText().toString();
            
            pst.setString(1,t_tag+"-"+t_group+"-"+t_subject+"-"+t_subject_code+"-"+t_duration+"-"+t_lectureName);
            
            String t_roomText = roomText.getText().toString();
            String t_StudentGroup = StudentGroup.getSelectedItem().toString();
            String t_batchComboBox = batchComboBox.getSelectedItem().toString();
            String t_DayComboBox = DayComboBox.getSelectedItem().toString();
            String t_timeComboBox = timeComboBox.getSelectedItem().toString();
            
            
            pst.setString(2, t_roomText);
            pst.setString(3, t_StudentGroup);
            pst.setString(4, t_batchComboBox);
            pst.setString(5, t_DayComboBox);
            pst.setString(6, t_timeComboBox);
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "Inserted Successfully");
            
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_addTimeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTimeSlot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTimeSlot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTimeSlot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTimeSlot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTimeSlot().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DayComboBox;
    private javax.swing.JComboBox<String> StudentGroup;
    private javax.swing.JButton addBut;
    private javax.swing.JButton addTime;
    private javax.swing.JComboBox<String> batchComboBox;
    private javax.swing.JLabel duration;
    private javax.swing.JLabel duration1;
    private javax.swing.JLabel group;
    private javax.swing.JLabel group1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lectureName;
    private javax.swing.JLabel lectureName1;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JTextField roomText;
    private javax.swing.JComboBox<String> setSession;
    private javax.swing.JLabel subject;
    private javax.swing.JLabel subject1;
    private javax.swing.JLabel subject_code;
    private javax.swing.JLabel subject_code1;
    private javax.swing.JLabel tag;
    private javax.swing.JLabel tag1;
    private javax.swing.JComboBox<String> timeComboBox;
    // End of variables declaration//GEN-END:variables
}
