/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Student;

import Student.year;
import Student.programme;
import Student.group;
import Student.groupID;
import Student.subgroupID;
import Student.subgroup;
import Student.tag;
import javax.swing.JFrame;


/**
 *
 * @author sangeeth
 */
public class studentDashboard extends javax.swing.JFrame {

    /**
     * Creates new form studentDashboard
     */
    public studentDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        view_group = new javax.swing.JButton();
        view_subgroup = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        view_year = new javax.swing.JButton();
        view_pro = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        view_groupid = new javax.swing.JButton();
        view_subgroupid = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        view_tag = new javax.swing.JButton();
        view_lecture_sub_menu4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(270, 180));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        view_group.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        view_group.setText("VIEW GROUP");
        view_group.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_groupActionPerformed(evt);
            }
        });
        jPanel2.add(view_group, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 11, 250, 74));

        view_subgroup.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        view_subgroup.setText("VIEW SUB-GROUP");
        view_subgroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_subgroupActionPerformed(evt);
            }
        });
        jPanel2.add(view_subgroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 95, 250, 74));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setPreferredSize(new java.awt.Dimension(270, 180));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        view_year.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        view_year.setText("VIEW YEAR");
        view_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_yearActionPerformed(evt);
            }
        });
        jPanel4.add(view_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 11, 250, 73));

        view_pro.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        view_pro.setText("VIEW PROGRAMME");
        view_pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_proActionPerformed(evt);
            }
        });
        jPanel4.add(view_pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 96, 250, 73));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setPreferredSize(new java.awt.Dimension(270, 180));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        view_groupid.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        view_groupid.setText("VIEW GROUPID");
        view_groupid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_groupidActionPerformed(evt);
            }
        });
        jPanel7.add(view_groupid, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 11, 250, 74));

        view_subgroupid.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        view_subgroupid.setText("VIEW SUBGROUPID");
        view_subgroupid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_subgroupidActionPerformed(evt);
            }
        });
        jPanel7.add(view_subgroupid, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 97, 250, 72));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setPreferredSize(new java.awt.Dimension(270, 180));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        view_tag.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        view_tag.setText("VIEW TAG");
        view_tag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_tagActionPerformed(evt);
            }
        });
        jPanel8.add(view_tag, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 11, 248, 74));

        view_lecture_sub_menu4.setBackground(java.awt.Color.lightGray);
        view_lecture_sub_menu4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        view_lecture_sub_menu4.setText("STUDENT DASHBOARD");
        view_lecture_sub_menu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_lecture_sub_menu4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(view_lecture_sub_menu4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(view_lecture_sub_menu4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void view_groupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_groupActionPerformed
        // TODO add your handling code here:
        group g = new group();
        g.setVisible(true);
        g.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_view_groupActionPerformed

    private void view_subgroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_subgroupActionPerformed
        // TODO add your handling code here:
        subgroup sub = new subgroup();
        sub.setVisible(true);
        sub.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dispose();
        
    }//GEN-LAST:event_view_subgroupActionPerformed

    private void view_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_yearActionPerformed
        // TODO add your handling code here:
        year year = new year();
        year.setVisible(true);
        year.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_view_yearActionPerformed

    private void view_proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_proActionPerformed
        // TODO add your handling code here:
        programme pro = new programme();
        pro.setVisible(true);
        pro.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_view_proActionPerformed

    private void view_groupidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_groupidActionPerformed
        // TODO add your handling code here:
        groupID gid = new groupID();
        gid.setVisible(true);
        gid.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_view_groupidActionPerformed

    private void view_subgroupidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_subgroupidActionPerformed
        // TODO add your handling code here:
        subgroupID subid = new subgroupID();
        subid.setVisible(true);
        subid.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_view_subgroupidActionPerformed

    private void view_tagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_tagActionPerformed
        // TODO add your handling code here:
        tag tag = new tag();
        tag.setVisible(true);
        tag.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_view_tagActionPerformed

    private void view_lecture_sub_menu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_lecture_sub_menu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_view_lecture_sub_menu4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_lecture_sub_menu2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton view_group;
    private javax.swing.JButton view_groupid;
    private javax.swing.JButton view_lecture_sub_menu2;
    private javax.swing.JButton view_lecture_sub_menu4;
    private javax.swing.JButton view_pro;
    private javax.swing.JButton view_subgroup;
    private javax.swing.JButton view_subgroupid;
    private javax.swing.JButton view_tag;
    private javax.swing.JButton view_year;
    // End of variables declaration//GEN-END:variables
}
