/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package workingdays;

import Commen.SubMenu;
import SpecialRoomAllocation.NavSpl;
import Student.studentDashboard;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import sesssionSpecial.sessionDashboard;

/**
 *
 * @author asvin
 */
public class UpdateWorkingDays extends javax.swing.JFrame {
    
     Connection conn = null;

    /**
     * Creates new form UpdateWorkingDays
     */
    public UpdateWorkingDays() {
        initComponents();
        conn = DbConn.ConnecrDb ();
        show_user();
    }

     public ArrayList<User> userList(){
        ArrayList<User> usersList = new ArrayList<>();
        try{
           //Class.forName("com.mysql.jdbc.Driver");
           
           //Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/tms","root","");
           String query = "SELECT* FROM workingdays";
           Statement st = conn.createStatement();
           ResultSet rs = st.executeQuery(query);
           User user;
           while(rs.next()){
               user = new User(rs.getString("semID"), rs.getInt("dayNo"),rs.getString("wDays"),rs.getString("wTimePerDay"),rs.getString("batch"));
               usersList.add(user);
           }
        }
        catch(Exception e ){
            JOptionPane.showMessageDialog(null,e);
        }
        return usersList;
    }
    public void show_user(){
        ArrayList<User> list = userList();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        Object[] row = new Object[7];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getsemID();
//            row[1]=list.get(i).getempName();
            row[1]=list.get(i).getdayNo();
            row[2]=list.get(i).getwDays();
            row[3]=list.get(i).getwTimePerDay();
            row[4]=list.get(i).getbatch();
           
            model.addRow(row);
            
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        wdays = new javax.swing.JLabel();
        Monday = new javax.swing.JCheckBox();
        Tuesday = new javax.swing.JCheckBox();
        Wednesday = new javax.swing.JCheckBox();
        Thursday = new javax.swing.JCheckBox();
        Friday = new javax.swing.JCheckBox();
        Saturday = new javax.swing.JCheckBox();
        Sunday = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        wTimePerDay = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dayNo = new javax.swing.JComboBox<>();
        comboBatch = new javax.swing.JComboBox<>();
        Update = new javax.swing.JButton();
        semID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        delete = new javax.swing.JButton();
        delete_semID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        resetUp = new javax.swing.JButton();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update Working Days & Hours");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(438, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26))
        );

        jTable1.setBackground(new java.awt.Color(204, 204, 0));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SemesterID", "NoOfWorkingDay/Week", "Working Days", "Working Time/Day", "Batch"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("No of Working Days per Week:");

        wdays.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        wdays.setText("Working Days:");

        Monday.setText("Monday");
        Monday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MondayActionPerformed(evt);
            }
        });

        Tuesday.setText("Tuesday");
        Tuesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TuesdayActionPerformed(evt);
            }
        });

        Wednesday.setText("Wednesday");
        Wednesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WednesdayActionPerformed(evt);
            }
        });

        Thursday.setText("Thursday");
        Thursday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThursdayActionPerformed(evt);
            }
        });

        Friday.setText("Friday");
        Friday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FridayActionPerformed(evt);
            }
        });

        Saturday.setText("Saturday");

        Sunday.setText("Sunday");
        Sunday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SundayActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Working Time per Day:");

        wTimePerDay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        wTimePerDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wTimePerDayActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Batch:");

        dayNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dayNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        dayNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayNoActionPerformed(evt);
            }
        });

        comboBatch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboBatch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "WeekDay", "WeekEnd" }));
        comboBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBatchActionPerformed(evt);
            }
        });

        Update.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Update.setText("UPDATE");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        semID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        semID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semIDActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Semester ID : ");

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        delete.setBackground(new java.awt.Color(210, 160, 138));
        delete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        delete_semID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Semester ID :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(delete_semID, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(delete)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete_semID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(delete)
                .addContainerGap())
        );

        resetUp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resetUp.setText("RESET");
        resetUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetUpActionPerformed(evt);
            }
        });

        jToggleButton14.setText("HOME");
        jToggleButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton14ActionPerformed(evt);
            }
        });

        jToggleButton13.setText("LECTURER");
        jToggleButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton13ActionPerformed(evt);
            }
        });

        jToggleButton16.setText("STUDENT");
        jToggleButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton16ActionPerformed(evt);
            }
        });

        jToggleButton18.setText("LOCATION");
        jToggleButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton18ActionPerformed(evt);
            }
        });

        jToggleButton17.setText("SESSION");
        jToggleButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton17ActionPerformed(evt);
            }
        });

        jToggleButton15.setText("TIMETABLE");
        jToggleButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton15ActionPerformed(evt);
            }
        });

        jDesktopPane2.setLayer(jToggleButton14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jToggleButton13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jToggleButton16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jToggleButton18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jToggleButton17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jToggleButton15, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jToggleButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToggleButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jToggleButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jToggleButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        jDesktopPane2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jToggleButton13, jToggleButton14, jToggleButton15, jToggleButton16, jToggleButton17, jToggleButton18});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(wdays)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dayNo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Monday)
                                            .addComponent(Thursday)
                                            .addComponent(Sunday))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Tuesday)
                                            .addComponent(Friday))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Saturday)
                                            .addComponent(Wednesday)))
                                    .addComponent(semID, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(wTimePerDay, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBatch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Update)
                                        .addGap(18, 18, 18)
                                        .addComponent(resetUp)))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(semID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(dayNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wdays)
                            .addComponent(Monday)
                            .addComponent(Tuesday)
                            .addComponent(Wednesday))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Thursday)
                            .addComponent(Friday)
                            .addComponent(Saturday))
                        .addGap(18, 18, 18)
                        .addComponent(Sunday)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(wTimePerDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(comboBatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Update)
                            .addComponent(resetUp))))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FridayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FridayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FridayActionPerformed

    private void SundayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SundayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SundayActionPerformed

    private void WednesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WednesdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WednesdayActionPerformed

    private void ThursdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThursdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThursdayActionPerformed
    String general_code;
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        String something = semID.getText();
        general_code = something;
        
        TableModel model = jTable1.getModel();
        semID.setText(model.getValueAt(i,0).toString());
//        empName.setText(model.getValueAt(i,1).toString());
       String dayNo1 = model.getValueAt(i,1).toString();
       switch(dayNo1){
        case "1":
           dayNo.setSelectedIndex(0);
           break;
        case "2":
           dayNo.setSelectedIndex(1);
           break;
        case "3":
           dayNo.setSelectedIndex(2);
           break;
        case "4":
           dayNo.setSelectedIndex(3);
           break;
        case "5":
           dayNo.setSelectedIndex(4);
           break;
        case "6":
           dayNo.setSelectedIndex(5);
           break;
        case "7":
           dayNo.setSelectedIndex(6);
           break;
       }
        String wdays = model.getValueAt(i,2).toString();
        switch(wdays){
            case "Monday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Monday Tuesday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Monday Wednesday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Monday Thursday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Monday Friday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Monday Saturday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break;
            case "Monday Sunday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;
            case "Tuesday ":
                Monday.setSelected(false);
                Tuesday.setSelected(true);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;  
                 case "TuesDay Wednesday ":
                Monday.setSelected(false);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "TuesDay ThursDay ":
                Monday.setSelected(false);
                Tuesday.setSelected(true);
                Wednesday.setSelected(false);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "TuesDay Friday ":
                Monday.setSelected(false);
                Tuesday.setSelected(true);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "TuesDay SaturDay ":
                Monday.setSelected(false);
                Tuesday.setSelected(true);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break;
            case "TuesDay Sunday ":
                Monday.setSelected(false);
                Tuesday.setSelected(true);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;
             case "Wednesday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;  
            case "Wednesday Thursday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(true);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;  
            case "Wednesday Friday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break; 
            case "Wednesday Saturday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break;  
            case "Wednesday Sunday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;  
            case "Thursday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;   
            case "Thursday Friday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(true);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;   
            case "Thursday Saturday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break;  
            case "Thursday Sunday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;  
            case "Friday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;   
            case "Friday Saturday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break;   
            case "Friday Sunday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;   
            case "Saturday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break;  
            case "Saturday Sunday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(true);
                break;  
            case "Sunday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;  
            case "Monday Tuesday Wednesday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;  
            case "Monday Tuesday Thursday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(false);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break; 
            case "Monday Tuesday Friday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;  
            case "Monday Tuesday Saturday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break; 
            case "Monday Tuesday Sunday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;  
            case "Monday Wednesday Thursday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(true);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;  
            case "Monday Wednesday Friday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;  
            case "Monday Wednesday Saturday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break; 
            case "Monday Wednesday Sunday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;  
            case "Monday Thursday Friday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(true);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;  
            case "Monday Thursday Saturday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break;
             case "Monday Thursday Sunday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;
             case "Monday Friday Saturday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(true);
                Sunday.setSelected(true);
                break;
             case "Monday Friday Sunday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;
            case "Monday Saturday Sunday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(true);
                break;
            case "Monday Tuesday Wednesday Thursday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Monday Tuesday Wednesday Friday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Monday Tuesday Wednesday Saturday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break;
            case "Monday Tuesday Wednesday Sunday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;
            case "Monday Tuesday Wednesday Thursday Friday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(true);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Monday Tuesday Wednesday Thursday Saturday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break;
            case "Monday Tuesday Wednesday Thursday Sunday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;
            case "Monday Tuesday Wednesday Thursday Friday Saturday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(true);
                Friday.setSelected(true);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break;
            case "Monday Tuesday Wednesday Thursday Friday Sunday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(true);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;
            case "Monday Tuesday Wednesday Thursday Friday Saturday Sunday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(true);
                Friday.setSelected(true);
                Saturday.setSelected(true);
                Sunday.setSelected(true);
                break;   
            default:
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(true);
                Friday.setSelected(true);
                Saturday.setSelected(true);
                Sunday.setSelected(true);
                break; 
                
                
        }
       
        wTimePerDay.setText(model.getValueAt(i,3).toString()); 
        String batch = model.getValueAt(i,4).toString();
        switch(batch){
            case "1 Hour":
                comboBatch.setSelectedIndex(0);
                break;
            case "30 Min":
                comboBatch.setSelectedIndex(1);
                break;
        }
         
        
    }//GEN-LAST:event_jTable1MouseClicked
   
    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        try{
           //Class.forName("com.mysql.jdbc.Driver");
           
           //Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/tms","root","");
           int row = jTable1.getSelectedRow();
           String value = (jTable1.getModel().getValueAt(row, 0).toString());
           String sem_ID = semID.getText();
           
           
//           String emp_Name = empName.getText();
           String day_No;
           day_No=dayNo.getSelectedItem().toString();
           //String w_days = wdays.getText();
           String w_days="";
          if(Monday.isSelected()){
              w_days+=Monday.getText()+" ";
          }
          if(Tuesday.isSelected()){
              w_days+=Tuesday.getText()+" ";
          }
          if(Wednesday.isSelected()){
              w_days+=Wednesday.getText()+" ";
          }
          if(Thursday.isSelected()){
              w_days+=Thursday.getText()+" ";
          }
          if(Friday.isSelected()){
              w_days+=Friday.getText()+" ";
          }
          if(Saturday.isSelected()){
              w_days+=Saturday.getText()+" ";
          }
          if(Sunday.isSelected()){
              w_days+=Sunday.getText()+" ";
          }
           String w_TimePerDay = wTimePerDay.getText();
           String batCh;
           batCh=comboBatch.getSelectedItem().toString();
           
           
           
          String query = "UPDATE workingdays SET  dayNo='"+day_No+"', wDays='"+w_days+"', wTimePerDay='"+w_TimePerDay+"', batch='"+batCh+"'";
          
          PreparedStatement pst = conn.prepareStatement(query);

          pst.executeUpdate();
         DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
         model.setRowCount(0);
         show_user();
         JOptionPane.showMessageDialog(null,"Updated Sucessfully!");
        }
        catch(Exception e ){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try{
        
        //Class.forName("com.mysql.jdbc.Driver");
       // Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/tms","root","");
        String query="DELETE FROM workingdays WHERE semID ="+delete_semID.getText();
        Statement st=conn.createStatement();
       
        
        st.executeUpdate(query);
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
         model.setRowCount(0);
       show_user();
         JOptionPane.showMessageDialog(null,"Deleted Sucessfully!");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }  
        
    }//GEN-LAST:event_deleteActionPerformed

    private void MondayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MondayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MondayActionPerformed

    private void TuesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TuesdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TuesdayActionPerformed

    private void wTimePerDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wTimePerDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wTimePerDayActionPerformed

    private void comboBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBatchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBatchActionPerformed

    private void dayNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayNoActionPerformed

    private void semIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semIDActionPerformed

    private void resetUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetUpActionPerformed
        // TODO add your handling code here:
         semID.setText("");
//        empName.setText("");
        dayNo.setSelectedIndex(0);
        Monday.setSelected(false);
        Tuesday.setSelected(false);
        Wednesday.setSelected(false);
        Thursday.setSelected(false);
        Friday.setSelected(false);
        Saturday.setSelected(false);
        Sunday.setSelected(false);
        wTimePerDay.setText("");
       
        comboBatch.setSelectedIndex(0);
        
    }//GEN-LAST:event_resetUpActionPerformed

    private void jToggleButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton14ActionPerformed

    private void jToggleButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton13ActionPerformed
        // TODO add your handling code here:
        SubMenu s = new SubMenu();
        s.setVisible(true);
        s.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_jToggleButton13ActionPerformed

    private void jToggleButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton16ActionPerformed
        // TODO add your handling code here:
        studentDashboard s = new studentDashboard();
        s.setVisible(true);
        s.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_jToggleButton16ActionPerformed

    private void jToggleButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton18ActionPerformed
        // TODO add your handling code here:
        NavSpl s = new NavSpl();
        s.setVisible(true);
        s.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_jToggleButton18ActionPerformed

    private void jToggleButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton17ActionPerformed
        // TODO add your handling code here:
        sessionDashboard s = new sessionDashboard();
        s.setVisible(true);
        s.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_jToggleButton17ActionPerformed

    private void jToggleButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton15ActionPerformed
        // TODO add your handling code here:
        TimeTableSystemManagementMain s = new TimeTableSystemManagementMain();
        s.setVisible(true);
        s.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_jToggleButton15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateWorkingDays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateWorkingDays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateWorkingDays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateWorkingDays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateWorkingDays().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Friday;
    private javax.swing.JCheckBox Monday;
    private javax.swing.JCheckBox Saturday;
    private javax.swing.JCheckBox Sunday;
    private javax.swing.JCheckBox Thursday;
    private javax.swing.JCheckBox Tuesday;
    private javax.swing.JButton Update;
    private javax.swing.JCheckBox Wednesday;
    private javax.swing.JComboBox<String> comboBatch;
    private javax.swing.JComboBox<String> dayNo;
    private javax.swing.JButton delete;
    private javax.swing.JTextField delete_semID;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JButton resetUp;
    private javax.swing.JTextField semID;
    private javax.swing.JTextField wTimePerDay;
    private javax.swing.JLabel wdays;
    // End of variables declaration//GEN-END:variables
}
